#!/bin/bash

if [[ $1 ]]; then
  printf -v file '%03d.c' "$1"
else
  files=([0-9][0-9][0-9].*)
  file=${files[-1]}
fi
if [[ -f $file ]]; then
  exec vim "$file"
else
  printf 'File not found: %s\n' "$file" >&2
  exit 1
fi
