#!/bin/bash

shopt -s extglob

if [[ $1 ]]; then 
  printf -v file '%03d.c' "$1"
else
  files=([0-9][0-9][0-9].*)
  tmp=${files[-1]} tmp=${tmp%.*} tmp=${tmp##+(0)}
  printf -v file '%03d.c' "$((tmp + 1))"
fi

if [[ ! -f $file ]]; then
  cat <<'EOF' > "$file"
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include "bignum.h"

int main(void) {

}
EOF
  vim "$file"
else 
  printf 'file already exists\n' >&2
fi
